name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Generate the snake SVG and GIF
      - uses: Platane/snk@v3
        with:
          github_user_name: RaviD98
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      # Publish the generated files to the output branch for GitHub Pages
      - name: Push snake to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output
          folder: dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
